---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
# Packages ----

library(dplyr, warn.conflicts = FALSE)
library(readr, warn.conflicts = FALSE)

# Functions ----

mvp_path <- function(...) fs::path_home("Downloads", "mvp", ...)

localize_beach <- function(data) {
  # Localize beach
  lookup_table <- tribble(
        ~where, ~english,
       "beach",     "US",
       "coast",     "US",
    "seashore",     "UK",
     "seaside",     "UK"
  )
  
  left_join(data, lookup_table)
}

celsify_temp <- function(data) {
  mutate(data, temp = if_else(english == "US", f_to_c(temp) * 5/9, temp))
}

f_to_c <- function(x) (x - 32) * 5/9

# Data ----

input_name <- "swim.csv"
input_path <- mvp_path("input", input_name)
input_path

raw <- read_csv(input_path, show_col_types = FALSE)
raw

# Clean ----


localized <- localize_beach(raw)

clean <- celsify_temp(localized)

clean

# Save ----

output_path <- mvp_path("output", paste0("clean_", input_name))
output_path

write_csv(clean, output_path)
```
